### ISSUE TITLE
GLSL Support

### ISSUE THREAD

**Issue by od0x0** [cucapra/caiman#13]
Caiman currently uses the version of wgsl that works with wgpu 0.12.  However, wgsl is unstable, poorly documented, and very incompatible in newer versions of wgpu.  As such, any examples we write will have a very short shelf-life and it's both unknown how many bugs we might find and also very probable that we will find them.

wgpu offers a SPIR-V pathway that would be easy to enable.  This would allow us to use the more mature GLSL (or HLSL).

Let's just start with the minimal support required to use GLSL instead of WGSL.  Compilation will be less direct than it is for WGSL, so the GLSL cannot be directly included in the IR or human-friendly IR.  Instead, we will need to manually invoke the glsl compiler (glslang) to generate SPIR-V ahead of running caimanc and link the SPIR-V in upon loading the .ron file.

- [ ] Add SPIR-V support in the backend/IR (ir.rs, codegen.rs, shadergen.rs)
- [ ] Add external SPIR-V file import capability to parsing of IR from .ron (frontend.rs)
- [ ] Pipeclean with caiman-test

**Comment by mjguynn** [comment]
Would it be useful to generate SPIR-V from GLSL as part of caimanc and then deploy that the output location? I wrote [some code back in June](https://github.com/Checkmate50/wgpu-rs/blob/master/wgpu/examples/spirv.rs) which could pretty easily be adapted to do this. It's mildly "hacky" since it's basically just a wrapper around the Vulkan SDK but it makes it pretty easy to do runtime compilation of GLSL and HLSL.
